singleQuote: false
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
bracketSpacing: true
endOfLine: auto
overrides:
    - files: '*.yaml'
      options:
          singleQuote: true
          printWidth: 120
          tabWidth: 4
          semi: false
